"""add checklist database (checklistProfile, ChecklistCategory, ChecklistItem, Document)

Revision ID: ff446467ff89
Revises: 87ce129de85a
Create Date: 2025-06-01 23:37:06.101531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff446467ff89'
down_revision = '87ce129de85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_checklist_profile_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_profile_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_profile_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_profile_user_id'), ['user_id'], unique=False)

    op.create_table('checklist_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['checklist_profile.id'], name='fk_checklist_category_profile_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_category_profile_id'), ['profile_id'], unique=False)

    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['checklist_category.id'], name='fk_checklist_item_category_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_item_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_item_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_item_is_completed'), ['is_completed'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=True),
    sa.Column('grouping_category_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_item.id'], name='fk_document_checklist_item_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grouping_category_id'], ['checklist_category.id'], name='fk_document_grouping_category_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['checklist_profile.id'], name='fk_document_profile_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_checklist_item_id'), ['checklist_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_grouping_category_id'), ['grouping_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_profile_id'))
        batch_op.drop_index(batch_op.f('ix_document_grouping_category_id'))
        batch_op.drop_index(batch_op.f('ix_document_checklist_item_id'))

    op.drop_table('document')
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_item_is_completed'))
        batch_op.drop_index(batch_op.f('ix_checklist_item_due_date'))
        batch_op.drop_index(batch_op.f('ix_checklist_item_category_id'))

    op.drop_table('checklist_item')
    with op.batch_alter_table('checklist_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_category_profile_id'))

    op.drop_table('checklist_category')
    with op.batch_alter_table('checklist_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_profile_status'))
        batch_op.drop_index(batch_op.f('ix_checklist_profile_due_date'))

    op.drop_table('checklist_profile')
    # ### end Alembic commands ###
